// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using extratinhos.Datasource;

#nullable disable

namespace extratinhos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240205125824_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("extratinhos.Entitys.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Limit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Limit = 100000L
                        },
                        new
                        {
                            Id = 2L,
                            Limit = 80000L
                        },
                        new
                        {
                            Id = 3L,
                            Limit = 1000000L
                        },
                        new
                        {
                            Id = 4L,
                            Limit = 10000000L
                        },
                        new
                        {
                            Id = 5L,
                            Limit = 500000L
                        });
                });

            modelBuilder.Entity("extratinhos.Entitys.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Entry", (string)null);
                });

            modelBuilder.Entity("extratinhos.Entitys.Entry", b =>
                {
                    b.HasOne("extratinhos.Entitys.Client", "Client")
                        .WithMany("Entrys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("extratinhos.Entitys.Client", b =>
                {
                    b.Navigation("Entrys");
                });
#pragma warning restore 612, 618
        }
    }
}
